name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest

    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  build:
    name: do the thing.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: agdf
      shell: powershell
      run: |
        Import-Module ./codespaces.psm1 -Force
        Start-Codespaces -Subscription '${{ secrets.SUBSCRIPTION_ID }}' -Plan '${{ secrets.PLAN_ID }}' -ArmToken '${{ secrets.ARM_TOKEN }}'
        Wait-Debugger
        ./testFile.ps1
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force -MaximumVersion 4.999.999
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester test -EnableExit
    - uses: actions/upload-artifact@master
      with:
        name: test-module
        path: .
