name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  test_Codespace_Action:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    name: A job to run Codespaces on ${{ matrix.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Start Codespaces
      shell: pwsh
      run: |
        Write-Host $pid
        Import-Module ./Codespaces.psm1
        Start-Codespaces -Subscription '${{ secrets.SUBSCRIPTION_ID }}' -Plan '${{ secrets.PLAN_ID }}' -ArmToken '${{ secrets.ARM_TOKEN }}'
        ./TestFile.ps1
    - name: Test Action
      id: test
      uses: ./TestAction