name: CI

on: [push]

jobs:
  build:
    name: do the thing.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Run a script
      run: pwsh -c '$PSVersionTable'
