name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest

    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  build:
    name: do the thing.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: TylerLeonhardt/container-action-github-ops@master
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester test -EnableExit
    - uses: actions/upload-artifact@master
      with:
        name: test-module
        path: .
